version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=phonebook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d phonebook"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/phonebook?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - DB_DSN=postgres://user:password@db:5432/phonebook?sslmode=disable

volumes:
  pgdata: