extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # gRPC receiver on port 4317.
      http:
        endpoint: "0.0.0.0:4318" # HTTP receiver on port 4318.

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:
  attributes:
    actions:
      - key: region
        value: west
        action: insert

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug:
    verbosity: detailed # Replaces 'logging' exporter; same verbosity level.

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes, batch]
      exporters: [otlp, debug] # Updated to 'debug'.
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug] # Updated to 'debug'.
  extensions: [health_check, zpages]