@baseUrl=http://localhost:8080
#@baseUrl=http://api:8080
###
GET {{baseUrl}}/contacts?page=1
Accept: application/json

###
POST {{baseUrl}}/contacts
Content-Type: application/json
Accept: application/json

{
    "city": 1,
    "country": 1,
    "first_name": "Niv2",
    "last_name": "Eliyahu",
    "phones": [
        {
            "type": "mobile",
            "number": "+1234567890"
        }
    ],
    "street": "123 Main St",
    "postal_code": "12345"
}

###
@contactId=16a4e190-c9ab-431a-8401-dde695875ea3
DELETE {{baseUrl}}/contacts?id={{contactId}}
Accept: application/json

###
@contactId=0ef57a66-ce41-4bea-8443-2578228c3f83
PUT {{baseUrl}}/contacts
Content-Type: application/json
Accept: application/json

{
    "id": "{{contactId}}",
    "city": 1,
    "country": 1,
    "first_name": "UpdatedFirstName",
    "last_name": "UpdatedLastName",
    "phones": [
        {
            "type": "mobile",
            "number": "+1234567890"
        }
    ],
    "street": "123 Updated St",
    "postal_code": "54321"
}


###
GET {{baseUrl}}/contacts/search?first_name=Niv
Accept: application/json

###
GET {{baseUrl}}/contacts/search?last_name=Eliyahu
Accept: application/json

###
GET {{baseUrl}}/contacts/search?full_name=Niv%20Eliyahu
Accept: application/json

###
#this should return no results
GET {{baseUrl}}/contacts/search?full_name=Niv2%20Eliyahu
Accept: application/json

###
GET {{baseUrl}}/contacts/search?phone=%2B1234567890
Accept: application/json

