@baseUrl=http://localhost:8080
###
GET {{baseUrl}}/contacts?page=1
Accept: application/json

###
POST {{baseUrl}}/contacts
Content-Type: application/json
Accept: application/json

{
    "city": 1,
    "country": 1,
    "first_name": "Niv2",
    "last_name": "Eliyahu",
    "phones": [
        {
            "type": "mobile",
            "number": "+1234567890"
        }
    ],
    "street": "123 Main St",
    "postal_code": "12345"
}

###
@contactIdToDelete="47b7ee66-0eb6-44b1-a41e-ab5b69c0d1fc"
DELETE {{baseUrl}}/contacts?id={{contactIdToDelete}}
Accept: application/json

###
@contactIdToUpdate=375f0535-2f49-4527-aa90-45214093b202
PUT {{baseUrl}}/contacts
Content-Type: application/json
Accept: application/json

{
    "id": "{{contactIdToUpdate}}",
    "city": 1,
    "country": 1,
    "first_name": "UpdatedFirstName",
    "last_name": "UpdatedLastName",
    "phones": [
        {
            "type": "mobile",
            "number": "+1235555555"
        }
    ],
    "street": "123 Updated St",
    "postal_code": "54321"
}


###
GET {{baseUrl}}/contacts/search?first_name=Jane
Accept: application/json

###
GET {{baseUrl}}/contacts/search?last_name=Johnson
Accept: application/json

###
GET {{baseUrl}}/contacts/search?full_name=Alice%Johnson
Accept: application/json

###
#this should return no results
GET {{baseUrl}}/contacts/search?full_name=Jane%Johnson
Accept: application/json

###

@phoneNumberWithPlus=442071234567
GET {{baseUrl}}/contacts/search?phone=%2B{{phoneNumberWithPlus}}
Accept: application/json

