basePath: /
definitions:
  dto.PhoneDTO:
    properties:
      number:
        type: string
      type:
        type: string
    type: object
  internal_delivery_http_endpoint.AddContactRequest:
    properties:
      city:
        type: string
      country:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone:
        $ref: '#/definitions/dto.PhoneDTO'
      postal_code:
        type: string
      street:
        type: string
    required:
    - city
    - country
    - first_name
    - phone
    - street
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A simple RESTful API for managing a phone book.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Phone Book API
  version: "1.0"
paths:
  /contacts:
    post:
      consumes:
      - application/json
      description: Add a new contact to the phone book
      parameters:
      - description: Contact to add
        in: body
        name: contact
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_endpoint.AddContactRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_delivery_http_endpoint.AddContactRequest'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Failed to save contact
          schema:
            type: string
      summary: Add a new contact
      tags:
      - contacts
swagger: "2.0"
